apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: gszxealwn-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/gszxealwn-java-springboot-gitops